name: Build Windows executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build executable bundle
        run: python scripts/build_exe.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotkey-cleaner-windows
          path: dist/hotkey-cleaner.zip
          if-no-files-found: error
          retention-days: 30
